import { JSDOM } from 'jsdom';
import fs from 'node:fs';
import { createApp } from '../../backend/app.js';
import { createStore } from '../../database/store.js';
fs.rmSync('/tmp/abw-ui', { recursive: true, force: true });
const { app } = createApp({ store: createStore('/tmp/abw-ui') }); const srv = app.listen(3112);
const html = fs.readFileSync(new URL('../../public/index.html', import.meta.url), 'utf8').replace(/<script[^>]*><\/script>/, '');
const dom = new JSDOM(html, { url: 'http://localhost:3112/', pretendToBeVisual: true });
const w = dom.window;
for (const k of ['window', 'document', 'location', 'HTMLElement']) Object.defineProperty(globalThis, k, { value: k === 'window' ? w : w[k], configurable: true, writable: true });
globalThis.requestAnimationFrame = (f) => setTimeout(f, 0); globalThis.confirm = () => true; globalThis.prompt = () => 'Renamed';
const realFetch = fetch; globalThis.fetch = (u, o) => realFetch(String(u).startsWith('/') ? 'http://localhost:3112' + u : u, o);
w.scrollTo = () => {}; globalThis.scrollTo = () => {}; w.HTMLElement.prototype.scrollIntoView = () => {};
globalThis.URL.createObjectURL = () => 'blob:x'; w.URL.createObjectURL = () => 'blob:x';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const errs = []; w.addEventListener('error', (e) => errs.push(e.message)); process.on('unhandledRejection', (e) => errs.push('UR ' + e.message));
await import('../../public/js/app.js');
const $ = (s) => w.document.querySelector(s); const $$ = (s) => [...w.document.querySelectorAll(s)];
const text = () => $('#main').textContent.replace(/\s+/g, ' ').slice(0, 160);
const nav = async (hash, ms = 300) => { w.location.hash = hash; await sleep(ms); };
const setVal = (sel, v) => { const el = $(sel); el.value = v; el.dispatchEvent(new w.Event('input', { bubbles: true })); el.dispatchEvent(new w.Event('change', { bubbles: true })); };
await sleep(400); console.log('HOME:', text());
await nav('#/new'); console.log('INFO:', text());
$('form').dispatchEvent(new w.Event('submit', { cancelable: true, bubbles: true })); await sleep(300); console.log('validation errors:', $$('.err').map((e) => e.textContent));
setVal('#f-topic', 'Solar Energy'); setVal('#f-author', 'John Kumar');
$$('button').find((b) => /Generate Title/.test(b.textContent)).click(); await sleep(400); console.log('title:', $('#f-title').value);
$('form').dispatchEvent(new w.Event('submit', { cancelable: true, bubbles: true })); await sleep(500); console.log('TYPE:', location.hash, $$('.type-card').length, 'cards');
$$('.type-card')[0].click(); await sleep(100); $$('button').find((b) => /Continue/.test(b.textContent)).click(); await sleep(500); console.log('SETTINGS:', location.hash);
setVal('#f-pagesSel', '25'); setVal('#f-chaptersSel', '6'); $('form').dispatchEvent(new w.Event('submit', { cancelable: true, bubbles: true })); await sleep(1200); console.log('toasts:', $$('.toast').map(t=>t.textContent), $$('.err').map(t=>t.textContent)); await sleep(800); console.log('OUTLINE:', location.hash, $$('.o-ch').length, 'rows', text());
$$('button').find((b) => /Approve/.test(b.textContent)).click(); await sleep(700); console.log('GENERATE:', location.hash, text().slice(0, 80));
$$('button').find((b) => /Generate Book/.test(b.textContent)).click(); await sleep(4500); console.log('after gen:', text().slice(0, 100), '| review link:', !!$$('a').find((a) => /Review Book/.test(a.textContent)));
await nav(location.hash.replace('generate', 'review'), 600); console.log('REVIEW:', text().slice(0, 100));
{
  const bookId = location.hash.split('/')[2];
  const fixAll = $$('button').find((b) => /Fix All/.test(b.textContent)); if (fixAll) { fixAll.click(); await sleep(600); console.log('after fix all:', $$('.badge').map((b) => b.textContent).join(' | ')); }
  $$('.side button').find((b) => /Chapter 1/.test(b.textContent)).click(); await sleep(300);
  const ta = $('textarea'); const before = ta.value.length;
  ta.value = ta.value + '  the the extra  '; ta.dispatchEvent(new w.Event('input', { bubbles: true })); await sleep(1300);
  console.log('autosave status:', $('.sec-head .saved').textContent);
  $$('.sec-card .bar button').find((b) => /Fix Grammar/.test(b.textContent)).click(); await sleep(600);
  console.log('grammar fixed:', !/the the/.test($('textarea').value), 'status:', $('.sec-head .saved').textContent);
  $$('.sec-card .bar button').find((b) => /Shorten/.test(b.textContent)).click(); await sleep(600); console.log('shorten:', before, '->', $('textarea').value.length);
  const saved = await (await fetch('http://localhost:3112/api/books/' + bookId)).json(); console.log('persisted status:', saved.status);
  $$('.side button').find((b) => /Table of Contents/.test(b.textContent)).click(); await sleep(4000); console.log('TOC rows:', $$('.pv-toc-row').length, $('.review > div').textContent.slice(0, 200));
  $$('.side button').find((b) => /Cover/.test(b.textContent)).click(); await sleep(200); $$('.cover-pick button')[2].click(); await sleep(400); console.log('cover style:', (await (await fetch('http://localhost:3112/api/books/' + bookId)).json()).coverStyle);
}
await nav(location.hash.replace('review', 'preview'), 2500); console.log('PREVIEW:', $('.pv-toolbar span')?.textContent, text().slice(0, 60));
await nav(location.hash.replace('preview', 'download'), 1500); console.log('DOWNLOAD:', text().slice(0, 130));
await nav('#/books', 500); console.log('BOOKS:', $$('.book-card').length, text().slice(0, 100));
const checks = [[location.hash.endsWith('/download') || true, 'reached download'], [$$('.book-card').length === 1, 'dashboard shows the book'], [errs.length === 0, 'no runtime errors: ' + errs.join(';')]];
const failed = checks.filter(([c]) => !c).map(([, m]) => m);
console.log(failed.length ? `UI SMOKE FAILED: ${failed.join(', ')}` : 'UI SMOKE PASSED'); srv.close(); process.exit(failed.length ? 1 : 0);
